name: Auto Update Metadata and Rebuild Packages

on:
  push:
    branches: 
      - main
    paths:
      - 'packages/core/raw-svgs/**'
  pull_request:
    paths:
      - 'packages/core/raw-svgs/**'

jobs:
  update-and-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: setup bun
        uses: oven-sh/setup-bun@v1
        
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: bun install

      - name: Update Metadata
        run: bun run ./packages/utils/src/scripts/update-metadata.ts

      - name: Rebuild Core Package
        run: bun run build:core

      - name: Rebuild React Package
        run: bun run build:react

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add packages/core/src/metadata/tokens.json packages/core packages/react
          git commit -m "Automatically update metadata and rebuild packages" || echo "No changes to commit"
          git push
